ROWS = 8
COLUMNS = 8
EMPTY_ROW = (COLUMNS) * ["_"]
SPACE = " "
UNDERSCORE = '_'
NONE_LIST = COLUMNS * [None]
BLACK = 'black'
WHITE = 'white'
ALPHABET_ROW = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
LETTER_OFFSET = 65
START = 0