ROWS = 8
COLUMNS = 8
EMPTY_ROW = (COLUMNS) * ["_"]
SPACE = " "
UNDERSCORE = '_'
NONE_LIST = COLUMNS * [None]
BLACK = 'black'
WHITE = 'white'
ALPHABET_ROW = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
LETTER_OFFSET = 65
START = 0
LEFT_CASTLE = 'left castle'
RIGHT_CASTLE = "right castle"
PROMOTION_LIST = ['queen', 'rook', 'knight', 'bishop']
DRAW_LIST = ['yes', 'no']
CASTLE = 'castle'